services:
  slackbot:
    container_name: slack_bot
    build:
      context: .

    command:
      - /bin/bash
      - -c
      - |
        python main.py
    restart: always

  fastapi:
    container_name: fastapi_route
    build:
      context: .

    command: uvicorn app_fastapi:api --reload --host 0.0.0.0 --port 8000 --log-level warning
    ports:
      - 8000:8000

    restart: always

#  ngrok:
#    image: wernight/ngrok
#    environment:
#      - NGROK_AUTH=${NGROK_AUTH}
#      - NGROK_PROTOCOL=http
#      - NGROK_PORT=8000
#    ports:
#      - "4040:4040"
