name: Init AWS

on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment
        type: choice
        required: true
        options:
          - prod

jobs:

  ecr_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create Repository
        continue-on-error: true
        run: |
          aws ecr create-repository --region ap-northeast-2 --repository-name slackbot

  image:
    runs-on: ubuntu-latest
    needs: [ ecr_build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true

  build_vpc:
    runs-on: ubuntu-latest
    needs: [ set_environment ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build VPC
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: slackbot-vpc
          template: .github/cloudformation/vpc.yml


  build_ecs:
    runs-on: ubuntu-latest
    needs: [ set_environment, build_vpc, deploy_backend_image ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build ECS
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: slackbot-ecs
          template: .github/cloudformation/ecs.yml
          parameter-overrides: >-
            ProjectName=slackbot,
           
